# Generated by Django 4.2 on 2023-04-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musinsa_erp', '0003_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
