# Generated by Django 4.2 on 2023-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_inventory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='decreased_inventory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
